version: '3'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Desafio@123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: desafio
      RABBITMQ_DEFAULT_PASS: Desafio@123
      RABBITMQ_DEFAULT_VHOST: /
  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
  eventstoredb:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_INSECURE=true 
      - EVENTSTORE_EXT_TCP_PORT=1113 
      - EVENTSTORE_HTTP_PORT=2113 
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113" 
      - "2113:2113"


